""" Vim settings

" Pathogen
call pathogen#infect()
call pathogen#helptags()

" No vi compatibility
set nocompatible

" Help force plugins to load correctly when turned back on below
filetype off

" Syntax highlighting
syntax on

" NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

""" Load pathogen plugins
" Clj-Kondo
let g:ale_linters = {'clojure': ['clj-kondo']}

" Rainbow parens
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
au VimEnter * RainbowParenthesesActivate
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" For proper plugin loading
filetype plugin indent on

" Leader key
let mapleader = ","

" Modeline security
set modelines=0

" Relative line numbers
set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

" Set backspacing
set backspace=indent,eol,start

" Set line numbering
set ruler

" Blink cursor on bell
set visualbell

" UTF-8 Encoding
set encoding=utf-8

" Whitespace and wrapping configuration
set wrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set noshiftround
set smarttab

" Status line configuration
set laststatus=2
set showcmd
set showmode

" Searching configuration
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

" Colors
set t_Co=256
set background=dark
colorscheme summerfruit256
