""" Vim settings

" Pathogen
call pathogen#infect()
call pathogen#helptags()

" No vi compatibility
set nocompatible

" Help force plugins to load correctly when turned back on below
filetype off

" Syntax highlighting
syntax on

""" Load pathogen plugins
" Rainbow parens
au VimEnter * RainbowParenthesesActivate
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" For proper plugin loading
filetype plugin indent on

" Leader key
let mapleader = ","

" Modeline security
set modelines=0

" Relative line numbers
set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

" Set line numbering
set ruler

" Blink cursor on bell
set visualbell

" UTF-8 Encoding
set encoding=utf-8

" Whitespace and wrapping configuration
set wrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set noshiftround
set smarttab

" Status line configuration
set laststatus=2
set showcmd
set showmode

" Searching configuration
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

" Colors
set t_Co=256
set background=dark
colorscheme slate
